openapi:
  project-title: Employee Salary Management API
  project-version: v11
  project-description: Management of employee salary
spring-doc:
  pathsToMatch: /api/**
spring:
  application:
    name: employee-salary-management
    description: management of employee salary
    profile: generic
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
    main:
      banner-mode: 'off '
  logging:
    pattern:
      console: '%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
        %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red}
        %clr(%m){faint}%n'
