server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:employee-salary-management}
    driver-class-name: org.h2.Driver
    username: ${POSTGRES_DB_USERNAME:sa}
    password: ${POSTGRES_DB_PASSWORD:sa}
  jpa:
    generate-ddl: true
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
  sql:
    init:
      mode: always
  application:
    profile: dev
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
    initialize-schema: ALWAYS